---
- name: Update package cache
  become: true
  pacman:
    update_cache: true
  changed_when: false

- name: Install base tools
  pacman:
    name:
      - git
      - go
      - vi
      - vim
    state: present

- name: Install dependencies for building AUR packages
  pacman:
    name:
      - base-devel   # Includes fakeroot and other tools needed for building
    state: present

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  lineinfile:
    path: /etc/sudoers.d/aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0440
    validate: 'visudo -cf %s'

- name: Clone yay sources
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
  become: yes
  become_user: aur_builder

- name: Build and install yay
  command:
    cmd: "makepkg -si --noconfirm && rm -rf /tmp/yay"
    chdir: /tmp/yay
  become: yes
  become_user: aur_builder
  args:
    creates: "/usr/bin/yay"
