---
- name: Update package cache
  become: true
  pacman:
    update_cache: true
  changed_when: false

- name: Install dependencies for building AUR packages
  pacman:
    name:
      - base-devel   # Includes fakeroot and other tools needed for building
      - git          # Required for cloning AUR repositories
    state: present

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Clone, build and install yay
  command:
    cmd: "git clone https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -si --noconfirm && rm -rf /tmp/yay"
  become: yes
  become_user: aur_builder
  args:
    creates: "/usr/bin/yay"
