---
- name: Install sound open firmware
  pacman:
    name:
      - sof-firmware
    state: present

- name: Install modem manager (5G)
  pacman:
    name:
      - modemmanager
      - usb_modeswitch
    state: present

- name: Enable modem manager service
  become: yes
  systemd:
    name: ModemManager
    enabled: yes
    state: started

- name: Configure automatic 5G fallback
  copy:
    src: "files/network_manager/99-wwan-fallback"
    dest: "/etc/NetworkManager/dispatcher.d/99-wwan-fallback"
    owner: root
    group: root
    mode: '0755'

- name: Install fingerprint reader daemon
  pacman:
    name:
      - fprintd
    state: present

- name: Enable Bluetooth service is started and enabled
  become: yes
  systemd:
    name: bluetooth
    enabled: yes
    state: started

- name: Ensure fingerprint auth is configured for sudo
  blockinfile:
    path: /etc/pam.d/sudo
    block: |
      auth      sufficient   pam_fprintd.so
    insertbefore: BOF
    state: present

- name: Install power manager tlp
  pacman:
    name:
      - tlp
      - tlp-rdw
    state: present

- name: Enable tlp service
  become: yes
  systemd:
    name: tlp
    enabled: yes
    state: started
