---
- name: Install sound open firmware
  pacman:
    name:
      - sof-firmware
    state: present

- name: Install modem manager (5G)
  pacman:
    name:
      - modemmanager
      - usb_modeswitch
    state: present

- name: Install fingerprint reader daemon
  pacman:
    name:
      - fprintd
    state: present
