---
- name: Install freetube
  kewlfft.aur.aur:
    name: freetube
    state: present
  become: yes
  become_user: aur_builder

- name: Ensure Flathub is added
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install plex desktop
  community.general.flatpak:
    name: tv.plex.PlexDesktop
    state: present

- name: Install video players
  pacman:
    name:
      - mplayer
      - vlc
    state: present

- name: Install zoom client
  kewlfft.aur.aur:
    name: zoom
    state: present
  become: yes
  become_user: aur_builder

- name: Install shotcut video editor
  pacman:
    name:
      - shotcut
    state: present
