---
- name: Install freetube
  kewlfft.aur.aur:
    name: freetube
    state: present
  become: yes
  become_user: aur_builder

- name: Install plex desktop
  kewlfft.aur.aur:
    name: plex-desktop
    state: present
  become: yes
  become_user: aur_builder

- name: Install video players
  pacman:
    name:
      - mplayer
      - vlc
    state: present
