---
- name: install flameshot screenshot tool
  pacman:
    name:
      - flameshot
    state: present

- name: install gnome disk utils
  pacman:
    name:
      - gnome-disk-utility
    state: present

- name: Install bitwarden cli client
  pacman:
    name:
      - bitwarden-cli
    state: present
