---
- name: Install docker
  pacman:
    name:
      - docker
    state: present

- name: Install docker compose
  pacman:
    name:
      - docker-compose
    state: present

- name: add current user to docker group
  user: name="{{ main_user }}"
        groups=docker
        append=yes

- name: Enable docker daemon
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started
