---
- name: Install android tools
  pacman:
    name:
      - android-tools
    state: present

- name: Ensure main user is in adbusers group
  user:
    name: "{{ main_user }}"
    groups: adbusers
    append: yes
