---
- name: Add Ruby plugin to asdf
  command: "/opt/asdf-vm/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git"
  become: yes
  become_user: "{{ main_user }}"

#- name: install mysql client
  #apt: pkg=mysql-client state=latest

#- name: install dev libs
  #apt: pkg=libmysqlclient-dev state=latest

#- name: install sqlite3
  #apt: pkg=sqlite3 state=latest

#- name: install postgresql dev lib
  #apt: pkg=libpq-dev state=latest

#- name: install graphviz
  #apt: pkg=graphviz state=latest

