---
- name: Add Ruby plugin to asdf
  command: "/opt/asdf-vm/bin/asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git"
  become: yes
  become_user: "{{ main_user }}"

- name: Add Ruby 3.2
  command: "/opt/asdf-vm/bin/asdf install ruby 3.2.5"
  become: yes
  become_user: "{{ main_user }}"

- name: Set default ruby
  command: "/opt/asdf-vm/bin/asdf global ruby 3.2.5"
  become: yes
  become_user: "{{ main_user }}"

- name: Install image tools
  pacman:
    name:
      - imagemagick
      - perl-image-exiftool
    state: present
