---

- name: Install Regolith desktop
  kewlfft.aur.aur:
    name: regolith-full
    state: present
  become: yes
  become_user: aur_builder

- name: Enable GDM service
  become: yes
  systemd:
    name: gdm.service
    enabled: yes
    state: started
