---
- name: Install KVM and virtualization packages
  become: true
  package:
    name:
      - qemu-full              # Full QEMU suite
      - libvirt                # libvirt daemon
      - virt-manager           # optional GUI
      - dnsmasq                # network bridging
      - virt-install           # CLI install tool
      - bridge-utils           # networking tools
    state: present

- name: Enable and start libvirtd
  become: true
  systemd:
    name: libvirtd
    enabled: true
    state: started

- name: Install vagrant
  kewlfft.aur.aur:
    name: vagrant
    state: present
  become: yes
  become_user: aur_builder

- name: Ensure vagrant-libvirt plugin is installed
  become: true
  shell: vagrant plugin install vagrant-libvirt
  args:
    creates: /usr/lib/vagrant/plugins/providers/libvirt

- name: Add user to libvirt and kvm groups
  become: true
  user:
    name: "{{ main_user }}"
    groups: [libvirt, kvm]
    append: true

- name: Verify that virtualization is supported
  command: grep -E -c '(vmx|svm)' /proc/cpuinfo
  register: virt_support
  changed_when: false
  failed_when: virt_support.stdout | int == 0
  tags: check

- name: Ensure default libvirt network is active
  become: true
  command: virsh net-autostart default
  changed_when: false
  ignore_errors: true

- name: Start default libvirt network
  become: true
  command: virsh net-start default
  changed_when: false
  ignore_errors: true
