---
- name: Remove legacy iptables if installed
  pacman:
    name: iptables
    state: absent
    force: yes

- name: Install KVM and virtualization packages
  become: true
  package:
    name:
      - qemu-full              # Full QEMU suite
      - libvirt                # libvirt daemon
      - virt-manager           # optional GUI
      - dnsmasq                # network bridging
      - virt-install           # CLI install tool
      - bridge-utils           # networking tools
      - iptables-nft          # nftables compatibility
      - ruby
    state: present

- name: Enable and start libvirtd
  become: true
  systemd:
    name: libvirtd
    enabled: true
    state: started

- name: Install vagrant
  kewlfft.aur.aur:
    name: vagrant
    state: present
  become: yes
  become_user: aur_builder

- name: Add user to libvirt and kvm groups
  become: true
  user:
    name: "{{ main_user }}"
    groups: [libvirt, kvm]
    append: true

- name: Verify that virtualization is supported
  command: grep -E -c '(vmx|svm)' /proc/cpuinfo
  register: virt_support
  changed_when: false
  failed_when: virt_support.stdout | int == 0
  tags: check

- name: Ensure default libvirt network is active
  become: true
  command: virsh net-autostart default
  changed_when: false
  ignore_errors: true

- name: Start default libvirt network
  become: true
  command: virsh net-start default
  changed_when: false
  ignore_errors: true

- name: Deploy nftables config
  copy:
    src: files/nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure nftables is enabled and running
  systemd:
    name: nftables
    enabled: true
    state: restarted
