---
- name: Install hyprland
  pacman:
    name:
      - hyprland
    state: present

- name: Install hyprland tools
  pacman:
    name:
      - swaylock
      - hyprpaper
      - pavucontrol
      - brightnessctl
      - blueman
      - hyprland-qtutils
      - wlr-randr
    state: present

- name: Install hyprland tools AUR
  kewlfft.aur.aur:
    name: flameshot-git
    state: present
  become: yes
  become_user: aur_builder

- name: Install hyprland screen sharing tools
  pacman:
    name:
      - pipewire
      - wireplumber
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-hyprland
    state: present

- name: Enable and start user services
  become_user: "{{ main_user }}"
  become: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + main_user) }}"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber

- name: Install kitty terminal
  pacman:
    name:
      - kitty
    state: present

- name: Install wofi menu
  pacman:
    name:
      - wofi
    state: present

- name: Install waybar
  pacman:
    name:
      - waybar
      - ttf-font-awesome
    state: present

- name: link hyprland config from profile
  become: true
  become_user: "{{ main_user }}"
  file:
    src: '~/git/setup/profile/hypr/hyprland.conf'
    dest: '~/.config/hypr/hyprland.conf'
    state: link
    force: true

- name: link waybar config from profile
  become: true
  become_user: "{{ main_user }}"
  file:
    src: '~/git/setup/profile/waybar/config'
    dest: '~/.config/waybar/config'
    state: link
    force: true

- name: link hyprpaper config from profile
  become: true
  become_user: "{{ main_user }}"
  file:
    src: '~/git/setup/profile/hypr/hyprpaper.conf'
    dest: '~/.config/hypr/hyprpaper.conf'
    state: link
    force: true

- name: link kitty terminal conf
  become: true
  become_user: "{{ main_user }}"
  file:
    src: '~/git/setup/profile/kitty/kitty.conf'
    dest: '~/.config/kitty/kitty.conf'
    state: link
    force: true

- name: Configure PAM for swaylock with fingerprint authentication
  copy:
    dest: /etc/pam.d/swaylock
    content: |
      auth      sufficient   pam_fprintd.so
      auth      required     pam_unix.so try_first_pass likeauth
      auth      include      login
    owner: root
    group: root
    mode: '0644'
